FROM node:latest

WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

ARG FIREBASE_ADMIN_TYPE
ARG FIREBASE_ADMIN_PROJECT_ID
ARG FIREBASE_ADMIN_PRIVATE_KEY_ID
ARG FIREBASE_ADMIN_PRIVATE_KEY
ARG FIREBASE_ADMIN_CLIENT_EMAIL
ARG FIREBASE_ADMIN_CLIENT_ID
ARG FIREBASE_ADMIN_AUTH_URI
ARG FIREBASE_ADMIN_TOKEN_URI
ARG FIREBASE_ADMIN_AUTH_PROVIDER_X509
ARG FIREBASE_ADMIN_CLIENT_X509

ARG FIREBASE_API_KEY
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_DATABASE_URL
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_STORAGE_BUCKET
ARG FIREBASE_MESSAGING_SENDER_ID
ARG FIREBASE_APP_ID
ARG FIREBASE_MEASUREMENT_ID
ARG FIREBASE_PUBLIC_VAPID_KEY

ARG WMS_API_KEY
ARG WMS_BASE_URL

ARG RECAPTCHA_SITE_KEY

ARG DASHBOARD_API_KEY

ENV HOST 0.0.0.0
ENV PORT 3000
ENV URL $URL
ENV NUXT_ENV_VERSION $NUXT_ENV_VERSION

ENV FIREBASE_ADMIN_TYPE $FIREBASE_ADMIN_TYPE
ENV FIREBASE_ADMIN_PROJECT_ID $FIREBASE_ADMIN_PROJECT_ID
ENV FIREBASE_ADMIN_PRIVATE_KEY_ID $FIREBASE_ADMIN_PRIVATE_KEY_ID
ENV FIREBASE_ADMIN_PRIVATE_KEY $FIREBASE_ADMIN_PRIVATE_KEY
ENV FIREBASE_ADMIN_CLIENT_EMAIL $FIREBASE_ADMIN_CLIENT_EMAIL
ENV FIREBASE_ADMIN_CLIENT_ID $FIREBASE_ADMIN_CLIENT_ID
ENV FIREBASE_ADMIN_AUTH_URI $FIREBASE_ADMIN_AUTH_URI
ENV FIREBASE_ADMIN_TOKEN_URI $FIREBASE_ADMIN_TOKEN_URI
ENV FIREBASE_ADMIN_AUTH_PROVIDER_X509 $FIREBASE_ADMIN_AUTH_PROVIDER_X509
ENV FIREBASE_ADMIN_CLIENT_X509 $FIREBASE_ADMIN_CLIENT_X509

ENV FIREBASE_API_KEY $FIREBASE_API_KEY
ENV FIREBASE_AUTH_DOMAIN $FIREBASE_AUTH_DOMAIN
ENV FIREBASE_DATABASE_URL $FIREBASE_DATABASE_URL
ENV FIREBASE_PROJECT_ID $FIREBASE_PROJECT_ID
ENV FIREBASE_STORAGE_BUCKET $FIREBASE_STORAGE_BUCKET
ENV FIREBASE_MESSAGING_SENDER_ID $FIREBASE_MESSAGING_SENDER_ID
ENV FIREBASE_APP_ID $FIREBASE_APP_ID
ENV FIREBASE_MEASUREMENT_ID $FIREBASE_MEASUREMENT_ID
ENV FIREBASE_PUBLIC_VAPID_KEY $FIREBASE_PUBLIC_VAPID_KEY

ENV WMS_API_KEY $WMS_API_KEY
ENV WMS_BASE_URL $WMS_BASE_URL

ENV RECAPTCHA_SITE_KEY $RECAPTCHA_SITE_KEY

ENV DASHBOARD_API_KEY $DASHBOARD_API_KEY

EXPOSE 3000

# start command
CMD [ "npm", "run", "start" ]