name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get last deployment timestamp on Netlify
      uses: fjogeleit/http-request-action@master
      id: lastDeployment
      with:
        url: 'https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}'
        method: 'GET'
        customHeaders: '{"User-Agent":"${{ secrets.NETLIFY_SITE_ID }} (${{ secrets.NETLIFY_USER_EMAIL }})","Authorization":"Bearer ${{ secrets.NETLIFY_ACCESS_TOKEN }}","Accept":"application/json"}'
    - name: Set last deployment timestamp as env variable
      env:
        PUBLISHED_DEPLOY: ${{ steps.lastDeployment.outputs.response.published_deploy }} 
      run: |
        if [ -z "$PUBLISHED_DEPLOY" ]
        then
          echo "LAST_DEPLOY=-1" >> $GITHUB_ENV
        else
          echo "LAST_DEPLOY=${{ steps.lastDeployment.outputs.response.published_deploy.published_at }}"" >> $GITHUB_ENV
        fi
    - name: Check last deployment timestamp value
      run: |
        echo ${{ env.LAST_DEPLOY }}